language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"
services:
  - redis-server
before_install:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then pecl channel-update pecl.php.net; fi;
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != 7.* ]]; then pecl install riak-beta; fi;
  - if [[ $TRAVIS_PHP_VERSION = '5.5' ]] ; then echo yes | pecl install apcu-4.0.10; fi;
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]] ; then echo yes | pecl install apcu-4.0.10; fi;
  - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then pecl config-set preferred_state beta; echo yes | pecl install apcu; fi;
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-add ./integration-tests/php.ini; fi;
before_script:
  - composer self-update
  - composer update --no-interaction $COMPOSER_OPTS
script:
  - vendor/bin/phpunit tests --coverage-text
  - ln -s vendor integration-tests/vendor
  - vendor/bin/phpunit integration-tests/LDDFeatureRequesterTest.php
