version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-5.5
      - test-5.6
      - test-7.0
      - test-7.1
      - test-7.2
      - integration-test

php-docker-template: &php-docker-template
  steps:
    - checkout
    - run:
        name: validate composer.json
        command: composer validate
    - run:
        name: install current dependencies
        command: composer install --no-progress
    - run:
        name: run tests with current dependency versions
        command: vendor/bin/phpunit --log-junit ~/phpunit/junit.xml --coverage-text tests
    - store_test_results:
        path: ~/phpunit
    - store_artifacts:
        path: ~/phpunit
    - run:
        name: run tests with highest available dependency versions
        command: composer update --no-progress && vendor/bin/phpunit tests
    - run:
        name: run tests with lowest available dependency versions
        # we skip this for 7.2 because the lowest compatible version of PHPUnit has a bug:
        # https://github.com/sebastianbergmann/comparator/pull/30
        command: |
          if [[ $CIRCLE_JOB != test-7.2 ]]; then
            composer update --prefer-lowest --no-progress && vendor/bin/phpunit tests;
          fi

jobs:
  test-5.6:
    <<: *php-docker-template
    docker:
      - image: circleci/php:5.6.34-cli-jessie
      - image: amazon/dynamodb-local
      - image: consul
      - image: redis
  test-7.0:
    <<: *php-docker-template
    docker:
      - image: circleci/php:7.0.28-cli-jessie
      - image: amazon/dynamodb-local
      - image: consul
      - image: redis
  test-7.1:
    <<: *php-docker-template
    docker:
      - image: circleci/php:7.1.15-cli-jessie
      - image: amazon/dynamodb-local
      - image: consul
      - image: redis
  test-7.2:
    <<: *php-docker-template
    docker:
      - image: circleci/php:7.2.3-cli-stretch
      - image: amazon/dynamodb-local
      - image: consul
      - image: redis

  test-5.5: # CircleCI doesn't provide a Docker image for 5.5
    machine:
      image: circleci/classic:latest # Ubuntu 14.04
    steps:
      - run:
          name: install PHP and Composer
          command: |
            sudo apt-get update &&
            sudo apt-get install circleci-php-5.5.36 &&
            php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');" &&
            sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - run:
          name: install Docker
          command: |
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" &&
            sudo apt-get -q update &&
            sudo apt-cache policy docker-ce &&
            sudo apt-get -qy install docker-ce
      - run: sudo apt-get -qy install redis-server
      - checkout
      - run:
          name: validate composer.json
          command: composer validate
      - run:
          name: install current dependencies
          command: composer install --no-progress
      - run:
          name: run php-cs-fixer
          command: vendor/bin/php-cs-fixer fix --diff --dry-run --verbose
      - run:
          name: start DynamoDB
          command: docker run -p 8000:8000 amazon/dynamodb-local
          background: true
      - run:
          name: download Consul
          command: wget https://releases.hashicorp.com/consul/0.8.0/consul_0.8.0_linux_amd64.zip
      - run:
          name: extract Consul
          command: unzip consul_0.8.0_linux_amd64.zip
      - run:
          name: start Consul
          command: ./consul agent -dev
          background: true
      - run:
          name: run tests
          command: vendor/bin/phpunit --log-junit ~/phpunit/junit.xml --coverage-text tests
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit

  integration-test:
    docker:
      - image: circleci/php:5.6.34-cli-jessie
      - image: redis
    steps:
      - checkout
      - run:
          name: setup apcu
          command: |
            pecl config-set php_ini /usr/local/etc/php/php.ini
            yes '' | sudo pecl install -f apcu-4.0.10 || true;
            echo "extension=apcu.so" | sudo tee -a /usr/local/etc/php/conf.d/apcu.ini;
            echo "apc.enable_cli = 1" | sudo tee -a /usr/local/etc/php/conf.d/apcu.ini
      - run: composer update --no-progress
      - run: vendor/bin/phpunit --log-junit ~/phpunit/junit.xml integration-tests/LDDFeatureRequesterTest.php
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit
